<?php include 'hint.php'; ?>
<html>
<head>
  <title> PERFECT TOUCH SALON AND SPA SERVICES Sales reports</title>
  <link rel="stylesheet" type="text/css" href="hidden_print.css">
<style type="text/css">
  th{
    font-size: 12px;
    text-transform: uppercase;
    text-align: top;

  }
</style>
</head>

<body class="hold-transition sidebar-mini" style="background: url('images/background.jpg'); background-size: cover;">
  <?php include 'datatableheader.php';
  include 'db_connect.php';?>
<center>
      <div>
        
  <form action="" method="POST">
        <span class="hidden-print btn btn-info"><label class="hidden-print" style="color: white">From:</label> <input type="Date" required="required" class="btn btn-info" id="date01" name="date1" placeholder="Enter Date to Search" >
        <label class="hidden-print" style="color: white">To:</label><input type="Date" required="required" id="date02" name="date2" class="btn btn-info" placeholder="Enter Date to Search">                  
        <button name="search" value="Generate" id="submit1" class="btn btn-info" onclick="show()"><i class="fa fa-search"></i></button>
      </span>           
  </form>
</div>
        <div style="max-width: 1000px;margin-top: 3px;">
          <div class="card">
            <div class="card-header">

              <h2 class="card-title"><a href="reportpage.php"><button class="btn btn-info">Back</button></a> <b> PERFECT TOUCH SALON AND SPA SERVICES Sales reports for today  <span id="span1"><script type="text/javascript">
                var dat = new Date();
                var dat1 = dat.toLocaleDateString();
                document.write(dat1);
              </script></span><span> generated by <?php echo $_SESSION["name"];?></span> </b></h2>
            </div>
            <!-- /.card-header -->
            <div class="card-body" id="card1" style="">
              <input type="button" name="sales" value="Print." style="float:right;"class="hidden-print" id="btnPrint">
              <table id="example1" class="table table-bordered table-striped" style="background-color: white;">
                <thead>
                <tr>
                  <th>Services</th>
                  <th>Cost</th>
                  <th>Customers</th>
                  <th>Staff</th>
                  <th>Posted by</th>
                  <th>Date</th>

                </tr>
                </thead>
                <tbody>
                <?php
  if(isset($_POST['search'])){
    $dat1 = $_POST['date1'];
    $dat2 = $_POST['date2'];
    //$produce = $_POST['produce'];
     // formating the dates
      $date = new DateTime($dat1);
      $dat1=$date->format('Y-m-d');
      $date = new DateTime($dat2);
      $date2 = $date->format('Y-m-d');
   
     
          $sql ="SELECT *
            FROM perfecttouch.sales WHERE transaction_date BETWEEN '$dat1' AND '$dat2'";
        $result = $connect->query($sql);
        if ($result-> num_rows >0) {
          while ($row = $result-> fetch_assoc()) {
            echo ("<tr><td><a href='#'>".$row["type"]."</a>"."</td>
                  <td>".$row["unit_price"]."</td>
                  <td>".$row["fullname"]."</td>
                  <td>".$row["staff"]."</td> 
                  <td>".$row["username"]."</td>                
                  <td>".$row["transaction_date"]."</td>
                  </tr>");
           
  }
       
    # code...
   
  $sql ="SELECT type,Sum(unit_price) as value
            FROM perfecttouch.sales WHERE transaction_date BETWEEN '$dat1' AND '$dat2'";
            $result = $connect->query($sql);
            if ($result-> num_rows >0) {
              while ($row = $result-> fetch_assoc()) {
               $total_sales = $row["value"];
           
            
  }

  echo "<tr><td ><span style='color:white;'>ZZ</span>Total</td><td>".$total_sales."</td><td></td><td></td><td></td><td>Amount</td></tr>";
       
  echo "</table>";
  echo "<table style= 'margin-top: 2px;' class='table table-responsive'>";
   echo "<hr>";
  echo "<tr><h3>The sales analysis are detailed below: <h3></tr>";
  echo "<tr>";
  echo "<th>TOTAL SALES VALUE IN THE PERIOD</th>
          <td><b>₦ ".($total_sales)."</b></td>";
  
  echo "</tr>";
  echo "<tr>";
  #echo "<th>EGGS BALANCE C/D IN THE WEEK</th><td> <b>".($eggbal)."</b></td><th>TOTAL BALANCE C/D IN THE WEEK</th>
          #".($balancecd)."</b></td>";
       echo "</tr>";    
  echo "<tr><th></th><td></td><th><b>Remarks</b></th>
          <td> <b>---------------</b></td></tr>";
 

 
  echo "</table>";
  echo "</div>";
  echo "<hr style='backgroud-color:red;'>";
}

  else {
    echo "No sales yet.";
 
}
}
}
//}

  

//}
    $connect->Close();
  //}
  ?>
                </tbody>
                <tfoot>
                <!--<tr>
                  <th>EGGS IN STOCK B/F</th>
                  <th>Eggs produced</th>
                  <th>Eggs sold</th>
                  <th>Eggs Bal B/F</th>
                  <th>Cash in hand</th>
                  <th>Total daily sales</th>
                  <th>Total daily expenses</th>
                  <th>Balance C/F</th>
                  <th>Remarks</th>
                </tr>-->
                </tfoot>
                
              </table>
            </div>
            <!-- /.card-body -->
          </div>
          
          <!-- /.card -->
    </div>
    </center>
        <!-- /.col -->
      <!-- /.row -->
    </section>
    <!-- /.content -->
  <!-- /.content-wrapper -->
  <!--<footer class="main-footer">-->
    <!--<div class="float-right d-none d-sm-block">
      <b>Version</b> 3.0.4
    </div>
    <strong>Copyright &copy; 2014-2019 <a href="http://adminlte.io">AdminLTE.io</a>.</strong> All rights
    reserved.
  </footer>-->

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
<!-- ./wrapper -->

<!-- jQuery -->
<?php include 'datatablefooter.php';?>
   
</body>




</html>
