<?php include 'hint.php'; ?>
<html>
<head>
  <title>PERFECT TOUCH SALON AND SPA SERVICE LISTS AND PRICES</title>
  <link rel="stylesheet" type="text/css" href="hidden_print.css">
<style type="text/css">
  th{
    font-size: 12px;
    text-transform: uppercase;
    text-align: top;

  }
</style>
</head>

<body class="hold-transition sidebar-mini" style="background: url('images/background.jpg'); background-size: cover;">
  <?php include 'datatableheader.php';
  include 'db_connect.php';?>
<center>
      <div>
        
  
</div>
        <div style="max-width: 1000px;margin-top: 3px;">
          <div class="card">
            <div class="card-header">

              <h2 class="card-title"><a href="reportpage.php"><button class="btn btn-info">Back</button></a> <b>PERFECT TOUCH SALON AND SPA SERVICES   <span id="span1"><script type="text/javascript">
                var dat = new Date();
                var dat1 = dat.toLocaleDateString();
                document.write(dat1);
              </script></span><span> generated by <?php echo $_SESSION["name"];?></span> </b></h2>
            </div>
            <!-- /.card-header -->
            <div class="card-body" id="card1" style="">
              <input type="button" name="sales" value="Print." style="float:right;"class="hidden-print" id="btnPrint">
              <table id="example1" class="table table-bordered table-striped" style="background-color: white;">
                <thead>
                <tr>
                  <th>services</th>
                  <th>Prices (₦)</th>
                  
                  <!--<th>Total daily expenses</th>
                  <th>Cash in hand</th>
                  <th>Balance C/D</th>-->
                  <th>Created date</th>
                  <th>Action</th>

                </tr>
                </thead>
                <tbody>
                <?php
 
    //$dat1 = $_POST['date1'];
    //$dat2 = $_POST['date2'];
    //$produce = $_POST['produce'];
     // formating the dates
      //$date = new DateTime($dat1);
      //$dat1=$date->format('Y-m-d');
      //$date = new DateTime($dat2);
      //$date2 = $date->format('Y-m-d');
   
     
          $sql ="SELECT *FROM perfecttouch.products";
        $result = $connect->query($sql);
        if ($result-> num_rows >0) {
          while ($row = $result-> fetch_assoc()) {?>

<tr>
          <td><?php echo $row['type']; ?></td>
          <td><?php echo $row['price']; ?></td>
          <td><?php echo $row['transaction_date'];?></td>

          <td ><a href="actions/action_updbt.php?id=<?php echo $row['id'];
          ?>" class="btn btn-danger" id="delete">Update</a></td>
          
          
      </tr> 

            
      <?php
           
  }
       
   
  
       
  echo "</table>";  
  echo "<tr><th></th><td></td><th><b>Remarks</b></th>
          <td> <b>---------------</b></td></tr>";

}

  else {
    echo "No sales yet.";
 
}

//}

  

//}
    $connect->Close();
  //}
  ?>
                </tbody>
                <tfoot>
                <!--<tr>
                  <th>EGGS IN STOCK B/F</th>
                  <th>Eggs produced</th>
                  <th>Eggs sold</th>
                  <th>Eggs Bal B/F</th>
                  <th>Cash in hand</th>
                  <th>Total daily sales</th>
                  <th>Total daily expenses</th>
                  <th>Balance C/F</th>
                  <th>Remarks</th>
                </tr>-->
                </tfoot>
                
              </table>
            </div>
            <!-- /.card-body -->
          </div>
          
          <!-- /.card -->
    </div>
    </center>
        <!-- /.col -->
      <!-- /.row -->
    </section>
    <!-- /.content -->
  <!-- /.content-wrapper -->
  <!--<footer class="main-footer">-->
    <!--<div class="float-right d-none d-sm-block">
      <b>Version</b> 3.0.4
    </div>
    <strong>Copyright &copy; 2014-2019 <a href="http://adminlte.io">AdminLTE.io</a>.</strong> All rights
    reserved.
  </footer>-->

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
<!-- ./wrapper -->

<!-- jQuery -->
<?php include 'datatablefooter.php';?>
<script type="text/javascript">
     function show() {
      document.getElementById("card1").style.display="block";
    }
      
  </script>
  <script type="text/javascript" src="print.js"></script>
</body>




</html>
