<?php include 'hint.php'; ?>
<html>
<head>
  <title>PERFECT TOUCH SALON AND SPA SERVICES STAFF LIST</title>
  <link rel="stylesheet" type="text/css" href="hidden_print.css">
<style type="text/css">
  th{
    font-size: 12px;
    text-transform: uppercase;
    text-align: top;

  }
  img{
    width: 100px;
    height: 100px;
    border-radius: 50px
  }
  img:hover{
    width: 200px;
    height: 200px;
  }
</style>
</head>

<body class="hold-transition sidebar-mini" style="background: url('images/background.jpg'); background-size: cover;">
  <?php include 'datatableheader.php';
  include 'db_connect.php';?>
<center>
      <div>
        
  <form action="" method="POST">
        <span class="btn btn-info">Generate report<button name="search" value="Generate" id="submit1" class="btn btn-info" onclick="show()"><i class="fa fa-search"></i></button></span>       
  </form>
</div>
        <div style="max-width: 1000px; margin-top: 4px;">
          <div class="card">
            <div class="card-header">

              <h2 class="card-title"><a href="reportpage.php"><button class="btn btn-info">Back</button></a> <b>PERFECT TOUCH SALON AND SPA SERVICES STAFF LIST  <span id="span1"><script type="text/javascript">
                var dat = new Date();
                var dat1 = dat.toLocaleDateString();
                document.write(dat1);
              </script></span>  <span> generated by <?php echo $_SESSION["name"];?></span></b></h2>
            </div>
            <!-- /.card-header -->
            <div class="card-body" id="card1" style="">
              <input type="button" name="sales" value="Print." style="float:right;"class="hidden-print" id="btnPrint">
              <table id="example1" class="table table-bordered table-striped" style="background-color: white; font-size: 14px;">
                <thead>
                <tr>
                  <th>#</th>
                   <th>Surname</th>
                  <th>First name</th>
                  <th>Phone no.</th>
                  <th>Gender</th>
                  <th>JOD</th>
                  <th>Salary</th>
                  <th>Passport</th>
                   <th>Action</th>
                  
                  <!--<th>Total daily expenses</th>
                  <th>Cash in hand</th>-->
                  
                </tr>
                </thead>
                <tbody>
                <?php
  if(isset($_POST['search'])){
    //$dat1 = $_POST['date1'];
    //$dat2 = $_POST['date2'];
    //$produce = $_POST['produce'];
     // formating the dates
      //$date = new DateTime($dat1);
      //$dat1=$date->format('Y-m-d');
      //$date = new DateTime($dat2);
      //$date2 = $date->format('Y-m-d');
   
     
          $sql ="SELECT *
            FROM perfecttouch.staff ORDER BY id";
        $result = $connect->query($sql);
        if ($result-> num_rows >0) {
          while ($row = $result-> fetch_assoc()) {
            $id = $row["id"];
            echo ("<tr><td>".$row["id"]."</td>
              <td><a href='#'>".$row["surname"]."</a>"."</td>
                  <td>".$row["fname"]."</td>
                  <td>".$row["phone"]."</td>
                  <td>".$row["gender"]."</td>
                  <td>".$row["jod"]."</td>
                  <td>".$row["salary"]."</td>
                  <td><img src='actions/documents/".$row['passport']."' ></td>
                    <td><a  class='btn btn-danger' href='update.php?id=".$id."'>Aproval</a>
                    <a  class='btn btn-danger' href='update.php?id=".$id."'>Detail</a></td>              
                  </tr>");
           
  }
       
    # code...
   
  $sql ="SELECT count(fname) as tstaff, sum(salary) as totalsal
            FROM perfecttouch.staff";
        $result = $connect->query($sql);
        if ($result-> num_rows >0) {
          while ($row = $result-> fetch_assoc()) {
          $tstaff = $row["tstaff"];
          $totalsal = $row["totalsal"];
           
            
  }
       
  echo "</table>";
  echo "<table style= 'margin-top: 2px;' class='table table-responsive'>";
   echo "<hr>";
  echo "<tr>";
  echo "<th>TOTAL NUNBER OF STAFF:&nbsp </th><td><b>".($tstaff)."</b></td>
  <th>TOTAL VALUE OF THE SALARY</th>
          <td><b>#".($totalsal)." </b></td>";
  
  echo "</tr>";
  #echo "<th>EGGS BALANCE C/D IN THE WEEK</th><td> <b>".($eggbal)."</b></td><th>TOTAL BALANCE C/D IN THE WEEK</th>
          #".($balancecd)."</b></td>";
       echo "</tr>";    
  echo "<tr><th></th><td></td><th><b>Remarks</b></th>
          <td> <b>---------------</b></td></tr>";
 

 
  echo "</table>";
  echo "</div>";
  echo "<hr>";
}

  else {
    echo "No sales yet.";
 
}
}
}
//}

  

//}
    $connect->Close();
  //}
  ?>
                </tbody>
                <tfoot>
                <!--<tr>
                  <th>EGGS IN STOCK B/F</th>
                  <th>Eggs produced</th>
                  <th>Eggs sold</th>
                  <th>Eggs Bal B/F</th>
                  <th>Cash in hand</th>
                  <th>Total daily sales</th>
                  <th>Total daily expenses</th>
                  <th>Balance C/F</th>
                  <th>Remarks</th>
                </tr>-->
                </tfoot>
                
              </table>
            </div>
            <!-- /.card-body -->
          </div>
          
          <!-- /.card -->
    </div>
    </center>
        <!-- /.col -->
      <!-- /.row -->
    </section>
    <!-- /.content -->
  <!-- /.content-wrapper -->
  <!--<footer class="main-footer">-->
    <!--<div class="float-right d-none d-sm-block">
      <b>Version</b> 3.0.4
    </div>
    <strong>Copyright &copy; 2014-2019 <a href="http://adminlte.io">AdminLTE.io</a>.</strong> All rights
    reserved.
  </footer>-->

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
<!-- ./wrapper -->

<!-- jQuery -->
<?php include 'datatablefooter.php';?>
<script type="text/javascript">
     function show() {
      document.getElementById("card1").style.display="block";
    }
      
  </script>
  <script src="print.js"></script>
</body>




</html>
