<?php include 'hint.php'; ?>
<html>
<head>
  <title> PERFECT TOUCH SALON AND SPA SERVICES SALES SUMMARY</title>
  <link rel="stylesheet" type="text/css" href="hidden_print.css">
<style type="text/css">
  th{
    font-size: 12px;
    text-transform: uppercase;
    text-align: top;

  }
</style>
</head>

<body class="hold-transition sidebar-mini" style="background: url('images/background.jpg'); background-size: cover;">
  <?php include 'datatableheader.php';
  include 'db_connect.php';?>
<center>
      <div>
        
  <form action="" method="POST">
        <span class="hidden-print btn btn-info"><label class="hidden-print" style="color: white">From:</label> <input type="Date" required="required" class="btn btn-info" id="date01" name="date1" placeholder="Enter Date to Search" >
        <label class="hidden-print" style="color: white">To:</label><input type="Date" required="required" id="date02" name="date2" class="btn btn-info" placeholder="Enter Date to Search">                  
        <button name="search" value="Generate" id="submit1" class="btn btn-info" onclick="show()"><i class="fa fa-search"></i></button>
      </span>           
  </form>
</div>
        <div style="max-width: 1000px;margin-top: 3px;">
          <div class="card">
            <div class="card-header">

              <h2 class="card-title"><a href="reportpage.php"><button class="btn btn-info">Back</button></a> <b> PERFECT TOUCH SALON AND SPA SERVICES SALES ACCOUNT REPORTS  <span id="span1"><script type="text/javascript">
                var dat = new Date();
                var dat1 = dat.toLocaleDateString();
                document.write(dat1);
              </script></span><span> generated by <?php echo $_SESSION["name"];?></span> </b></h2>
            </div>
            <!-- /.card-header -->
            <div class="card-body" id="card1" style="">
              <input type="button" name="sales" value="Print." style="float:right;"class="hidden-print" id="btnPrint">
              <table id="example1" class="table table-bordered table-striped" style="background-color: white;">
                <thead>
                <tr>
                  <th>SALES</th>
                  <th>₦</th>
                  <th>TOTAL EXPENSES</th>
                  <TH>CASH AT HAND</TH>
                 
                  <th>Date</th>

                </tr>
                </thead>
                <tbody>
                <?php
  if(isset($_POST['search'])){
    $dat1 = $_POST['date1'];
    $dat2 = $_POST['date2'];
    //$produce = $_POST['produce'];
     // formating the dates
      $date = new DateTime($dat1);
      $dat1=$date->format('Y-m-d');
      $date = new DateTime($dat2);
      $date2 = $date->format('Y-m-d');
      $holder = " ";
   
     
          $sql ="SELECT SUM(amount) AS amount, paymethod, transaction_date
            FROM perfecttouch.payments WHERE transaction_date BETWEEN '$dat1' AND '$dat2'
            GROUP BY paymethod";
        $result = $connect->query($sql);
        if ($result-> num_rows >0) {
          while ($row = $result-> fetch_assoc()) {
            echo ("<tr><td><b><a href='#'>".$row["paymethod"]."</a>"."</b></td>
                  <td><b>".$row["amount"]."</b></td>
                  <td>".$holder."</td>
                  <td></td>
                  <td><b>".$row["transaction_date"]."</b></td>
                  
                  </tr>");
           
  }
       
    # code...
   
  $sql ="SELECT Sum(amount) as a2
            FROM perfecttouch.payments WHERE transaction_date BETWEEN '$dat1' AND '$dat2'";
            $result = $connect->query($sql);
            if ($result-> num_rows >0) {
              while ($row = $result-> fetch_assoc()) {
               $total_sales = $row["a2"];
           
      
         
  }
  $sql ="SELECT Sum(amount) as expense
            FROM perfecttouch.expenses WHERE transaction_date BETWEEN '$dat1' AND '$dat2'";
            $result = $connect->query($sql);
            if ($result-> num_rows >0) {
              while ($row = $result-> fetch_assoc()) {
               $expense = $row["expense"];
           
      
         
  }

  $sql ="SELECT Sum(amount) as cash
            FROM perfecttouch.payments WHERE  transaction_date BETWEEN '$dat1' AND '$dat2' AND paymethod = 'cash'";
            $result = $connect->query($sql);
            if ($result-> num_rows >0) {
              while ($row = $result-> fetch_assoc()) {
               $cash = $row["cash"];

               $cashinhand = ($cash - $expense);
           
      
         
  }
echo "<th ><b><span style='color:whitesmoke;'>z</span>Total</th><th><b>".$total_sales."</b></th><th><b>".$expense."</b></th><th><b>".$cashinhand."</b></th><th></th></b>";
  
 

 
  
}

  else {
    echo "No sales yet.";
 
}
}
}
}

  

}
    $connect->Close();
  //}
  ?>
                </tbody>
                <tfoot>
                
                </tfoot>
                
              </table>
            </div>

            <!-- /.card-body -->
          </div>
          
          <!-- /.card -->
    </div>
    </center>
        <!-- /.col -->
      <!-- /.row -->
    </section>


    <!-- /.content -->
  <!-- /.content-wrapper -->
  <!--<footer class="main-footer">-->
    <!--<div class="float-right d-none d-sm-block">
      <b>Version</b> 3.0.4
    </div>
    <strong>Copyright &copy; 2014-2019 <a href="http://adminlte.io">AdminLTE.io</a>.</strong> All rights
    reserved.
  </footer>-->

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
<!-- ./wrapper -->

<!-- jQuery -->
<?php include 'datatablefooter.php';?>
   
</body>




</html>
