<?php include 'hint.php'; ?>
<html>
<head>
  <title>PERFECT TOUCH SALON AND SPA SERVICES</title>
  <link rel="stylesheet" type="text/css" href="hidden_print.css">
<style type="text/css">
  th{
    font-size: 12px;
    text-transform: uppercase;
    text-align: top;

  }
</style>
</head>

<body class="hold-transition sidebar-mini" style="background: url('images/background.jpg'); background-size: cover;">
  <?php include 'datatableheader.php';
  include 'db_connect.php';?>
<center>
      <div>
        
  <form action="" method="POST">
        <span class="btn btn-info">Generate report<button name="search" value="Generate" id="submit1" class="btn btn-info" onclick="show()"><i class="fa fa-search"></i></button></span>       
  </form>
</div>
        <div style="max-width: 1000px; margin-top: 4px;">
          <div class="card">
            <div class="card-header">

              <h2 class="card-title"><a href="front.php"><button class="btn btn-info">Back</button></a> <b>Users reports for today  <span id="span1"><script type="text/javascript">
                var dat = new Date();
                var dat1 = dat.toLocaleDateString();
                document.write(dat1);
              </script></span>  <span> generated by <?php echo $_SESSION["name"];?></span></b></h2>
              <p>
                <?php if (isset($_SESSION["disabled"])) {
                  echo $_SESSION["disabled"];
                  unset($_SESSION["disabled"]);
                  # code...
                } ?>
              </p>
            </div>
            <!-- /.card-header -->
            <div class="card-body" id="card1" style="">
              <input type="button" name="sales" value="Print." style="float:right;"class="hidden-print" id="btnPrint">
              <table id="example1" class="table table-bordered table-striped" style="background-color: white; font-size: 14px;">
                <thead>
                <tr>
                   <th>Username</th>
                  <th>First name</th>
                  <th>last name</th>
                  <th>Phone</th>
                  <th>Date</th>
                  <th>Status</th>
                  <!--<th>Cash in hand</th>
                  <th>Balance C/D</th>-->
                  <th>Action</th>

                </tr>
                </thead>
                <tbody>
                <?php
  if(isset($_POST['search'])){
    //$dat1 = $_POST['date1'];
    //$dat2 = $_POST['date2'];
    //$produce = $_POST['produce'];
     // formating the dates
      //$date = new DateTime($dat1);
      //$dat1=$date->format('Y-m-d');
      //$date = new DateTime($dat2);
      //$date2 = $date->format('Y-m-d');
   
     
          $sql ="SELECT id, username, fname,lname,phone,user_access, transaction_date
            FROM perfecttouch.accounts";
        $result = $connect->query($sql);
        if ($result-> num_rows >0) {
          while ($row = $result-> fetch_assoc()) {
            $status = $row["user_access"];

            if ($status == 0) {
              $status = 'disabled';
            }
            else{

                   $status = 'active';

              # code...
            }
              # code...
          
            ?>


      <tr>
          <td><?php echo $row['username']; ?></td>
          <td><?php echo $row['fname']; ?></td>
          <td><?php echo $row['lname']; ?></td>
          <td><?php echo $row['phone']; ?></td>
          <td><?php echo $row['transaction_date']; ?></td>
          <td><?php echo $status;?></td>

          <td ><a href="actions/action_disable.php?id=<?php echo $row['id'];
          ?>" class="btn btn-danger" id="delete">Disable</a></td>
          
          
      </tr> 

             <?php
           
  }

    $sql ="SELECT id, username, COUNT(username) as emply
            FROM perfecttouch.accounts";
        $result = $connect->query($sql);
        if ($result-> num_rows >0) {
          while ($row = $result-> fetch_assoc()) {
            $temply = $row["emply"];

       
    }
   

    
  echo "</table>";
  
       echo "</tr>";    
  echo "<tr><th>No of staff </th><td> <b>".($temply)." "."</b></td><th><b>Remarks</b></th>
          <td> <b>---------------</b></td></tr>";
 

 
  echo "</table>";
  echo "</div>";
  echo "<hr>";
}

  else {
    echo "No sales yet.";
 
}

}
}

  

//}
    $connect->Close();
  //}
  ?>
                </tbody>
                <tfoot>
                <!--<tr>
                  <th>EGGS IN STOCK B/F</th>
                  <th>Eggs produced</th>
                  <th>Eggs sold</th>
                  <th>Eggs Bal B/F</th>
                  <th>Cash in hand</th>
                  <th>Total daily sales</th>
                  <th>Total daily expenses</th>
                  <th>Balance C/F</th>
                  <th>Remarks</th>
                </tr>-->
                </tfoot>
                
              </table>
            </div>
            <!-- /.card-body -->
          </div>
          
          <!-- /.card -->
    </div>
    </center>
        <!-- /.col -->
      <!-- /.row -->
    </section>
    <!-- /.content -->
  <!-- /.content-wrapper -->
  <!--<footer class="main-footer">-->
    <!--<div class="float-right d-none d-sm-block">
      <b>Version</b> 3.0.4
    </div>
    <strong>Copyright &copy; 2014-2019 <a href="http://adminlte.io">AdminLTE.io</a>.</strong> All rights
    reserved.
  </footer>-->

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
<!-- ./wrapper -->

<!-- jQuery -->
<?php include 'datatablefooter.php';?>
<script type="text/javascript">
     function show() {
      document.getElementById("card1").style.display="block";
    }
      
  </script>
  <script src="print.js"></script>
</body>




</html>
